name: Tests

on:
  push:
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.0', '8.1']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate composer.json
        run: composer validate --strict

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          php-version: "${{ matrix.php }}"
          tools: composer

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --no-suggest --optimize-autoloader

      - name: Run Tests
        run: php vendor/bin/phpunit --verbose --coverage-text
