name: Tests

on:
  push:
  pull_request:
  
jobs:
  integration:
    runs-on: Ubuntu-20.04
    
    strategy:
      matrix:
        php: ['7.3', '7.4', '8.0']
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php }}"
          tools: composer        
          
      - name: Install Composer dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
          
      - name: Run Tests
        run: php bin/phpunit
